### ISSUE TITLE
Plasma 6 support

### ISSUE THREAD

**Issue by filipesaraiva** [alex1701c/krunner-firefox#7]
Hello, I had this plugin installed in my past Plasma 5. Now with Plasma 6 release, I compiled and installed the plugin again but looks like it is not working.

Do you know if the plugin supports Plasma 6?

**Comment by alex1701c** [comment]
Have you pulled the latest release and reran the install script?

**Comment by filipesaraiva** [comment]
Sure, I pull the repository, compiled and installed using the script. I killed krunner before install the plugin and started after.

I got this follow message after run krunner. Maybe is it related?

```krunner
Can not find a firefox.desktop or firefox-esr.desktop file in ~/.local/share/applications/
```

**Comment by alex1701c** [comment]
Hmm, this is weird. I would need to check how the file is initialized. It has been a bunch of years since I wrote the code

**Comment by alex1701c** [comment]
@filipesaraiva Please confirm if the issue is fixes for you
